In [ ]:
! pip install cassandra-driver

Collecting cassandra-driver
  Downloading cassandra_driver-3.29.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.9/18.9 MB 21.4 MB/s eta 0:00:00
Collecting geomet<0.3,>=0.1 (from cassandra-driver)
  Downloading geomet-0.2.1.post1-py3-none-any.whl (18 kB)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from geomet<0.3,>=0.1->cassandra-driver) (8.1.7)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from geomet<0.3,>=0.1->cassandra-driver) (1.16.0)
Installing collected packages: geomet, cassandra-driver
Successfully installed cassandra-driver-3.29.1 geomet-0.2.1.post1

In [ ]:
import pandas as pd
from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
import warnings
warnings.filterwarnings('ignore')

In [ ]:
astra_db = {
'cloud_config': {'secure_connect_bundle': '/content/secure-connect-customeranalysis.zip'},
'auth_provider': PlainTextAuthProvider(username='token', password='AstraCS:JphZZWYWfCZYupdhFOZdYudP:89bb593d93b06e8c52e2fdd088bf3d8f5421ccc40e88290dfcd4828d7590cd08')
}
cluster = Cluster(cloud=astra_db['cloud_config'], auth_provider=astra_db['auth_provider'])
session = cluster.connect()

WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for 2dba9a48-6ea0-46ab-95d3-85b158db43b7-eu-west-1.db.astra.datastax.com:29042:98a2cd7e-fa1b-3950-942e-42af495c4248. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 5 for 2dba9a48-6ea0-46ab-95d3-85b158db43b7-eu-west-1.db.astra.datastax.com:29042:98a2cd7e-fa1b-3950-942e-42af495c4248. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 5 to 4 for 2dba9a48-6ea0-46ab-95d3-85b158db43b7-eu-west-1.db.astra.datastax.com:29042:98a2cd7e-fa1b-3950-942e-42af495c4248. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Found multiple hosts with the same endpoint (2dba9a48-6ea0-46ab-95d3-85b158db43b7-eu-west-1.db.astra.datastax.com:29042:98a2cd7e-fa1b-3950-942e-42af495c4248). Excluding peer 10.0.0.2

In [ ]:
keyspace = 'customer_db'
table = 'customer_personality'
query = f"SELECT * FROM {keyspace}.{table};"
result_set = session.execute(query)

In [ ]:
result_set.column_names

['ID',
 'Response',
 'AcceptedCmp1',
 'AcceptedCmp2',
 'AcceptedCmp3',
 'AcceptedCmp4',
 'AcceptedCmp5',
 'Complain',
 'Dt_Customer',
 'Education',
 'Income',
 'Kidhome',
 'Marital_Status',
 'MntFishProducts',
 'MntFruits',
 'MntGoldProds',
 'MntMeatProducts',
 'MntSweetProducts',
 'MntWines',
 'NumCatalogPurchases',
 'NumDealsPurchases',
 'NumStorePurchases',
 'NumWebPurchases',
 'NumWebVisitsMonth',
 'Recency',
 'Teenhome',
 'Year_Birth',
 'Z_CostContact',
 'Z_Revenue']

In [ ]:
df = pd.DataFrame(result_set, columns=result_set.column_names)

In [ ]:
df.head()

,ID,Response,AcceptedCmp1,AcceptedCmp2,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,Complain,Dt_Customer,Education,...,NumCatalogPurchases,NumDealsPurchases,NumStorePurchases,NumWebPurchases,NumWebVisitsMonth,Recency,Teenhome,Year_Birth,Z_CostContact,Z_Revenue
0,1584,0,0,0,0,0,0,0,01-04-2014,Graduation,...,1,6,5,8,8,79,0,1977,3,11
1,7034,0,0,0,0,0,0,0,01-09-2013,2n Cycle,...,0,2,3,2,8,34,0,1978,3,11
2,6428,0,0,0,0,0,0,0,03-05-2014,PhD,...,8,1,7,1,0,37,0,1950,3,11
3,9973,0,0,0,0,0,0,0,17-10-2012,Graduation,...,1,3,8,7,7,28,2,1963,3,11
4,9495,0,0,0,0,0,0,0,08-05-2013,Graduation,...,8,1,6,2,1,29,0,1982,3,11

In [ ]:
# Don't forget to close the connection when done
session.shutdown()
cluster.shutdown()